title: Brian's First GitHub Site
author: brianpmccann
email: brianpmccann@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 This is my first GitHub site, I hoping to blog faster than I ever did in WordPress.

# social links
twitter_username: brianpmccann
github_username:  brianpmccann

show_excerpts: true # set to false to remove excerpts on the homepage
